### ISSUE TITLE
Unable to compile frontend 

### ISSUE THREAD

**Issue by pvssrikanth** [ustropo/websocket-example#1]
Dear Sir,
I am unable to compile frontend 

Open the browser in `localhost:3000` and you must see a chart being updated every second.
(venv) iibadmin@iibadmin-uat-ubuntu:~/srik/ws/websocket-example$ yarn install 
yarn install v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.07s.
(venv) iibadmin@iibadmin-uat-ubuntu:~/srik/ws/websocket-example$ yarn start
yarn run v1.22.10
error Couldn't find a package.json file in "/home/iibadmin/srik/ws/websocket-example"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(venv) iibadmin@iibadmin-uat-ubuntu:~/srik/ws/websocket-example$ 

error Couldn't find a package.json file in "/home/iibadmin/srik/ws/websocket-example"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(venv) iibadmin@iibadmin-uat-ubuntu:~/srik/ws/websocket-example$ ls
backend  frontend  node_modules  README.md  yarn.lock
(venv) iibadmin@iibadmin-uat-ubuntu:~/srik/ws/websocket-example$ cd frontend/
(venv) iibadmin@iibadmin-uat-ubuntu:~/srik/ws/websocket-example/frontend$ ls
package.json  public  src  yarn.lock
(venv) iibadmin@iibadmin-uat-ubuntu:~/srik/ws/websocket-example/frontend$ yarn start
yarn run v1.22.10
$ react-scripts start
/bin/sh: 1: react-scripts: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(venv) iibadmin@iibadmin-uat-ubuntu:~/srik/ws/websocket-example/frontend$ 

I am using ubunt18

Kindly help how to compile this frount end by sending email to srikanthpvs@gmail.com

Thanks in advance
srikanth

**Comment by ustropo** [comment]
To compile you should be in the `frontend` folder:

- cd frontend
- yarn install
- yarn start

**Comment by pvssrikanth** [comment]
Dear Sir,
Thanks for your prompt reply, really appreciate it.


I was  in frontend only

I did same yarn  install  and yarn start

But now i will do your earlier email ignore commands engine and then test
