### ISSUE TITLE
Unable to run yarn command frontend 

### ISSUE THREAD

**Issue by pvssrikanth** [ustropo/websocket-example#2]
Sir

ackage.json  public  src  yarn.lock
(venv) iibadmin@iibadmin-uat-ubuntu:~/srik/ws/websocket-example/frontend$ yarn install 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error jest-diff@26.6.2: The engine "node" is incompatible with this module. Expected version ">= 10.14.2". Got "8.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
(venv) iibadmin@iibadmin-uat-ubuntu:~/srik/ws/websocket-example/frontend$ 

I donnot know how to resolve this issue.

kindly help srikanthpvs@gmail.com

Thanking

**Comment by ustropo** [comment]
You can try these:

- Upgrade your nodejs version
- Or Run with the option `--ignore-engines`:
`
yarn install --ignore-engines
`

**Comment by pvssrikanth** [comment]
Dear Sir,
I am using ubunt18.

still facing error , Kindly help in resolution.

(venv) ***@***.***:~/srik/ws/websocket-example/frontend$
yarn install --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info ***@***.***: The platform "linux" is incompatible with this module.
info ***@***.***" is an optional dependency and failed compatibility
check. Excluding it from installation.
info ***@***.***: The platform "linux" is incompatible with this module.
info ***@***.***" is an optional dependency and failed compatibility
check. Excluding it from installation.
info ***@***.***: The platform "linux" is incompatible with this module.
info ***@***.***" is an optional dependency and failed compatibility
check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @***@***.***" has unmet peer dependency
***@***.***/dom@>=7.21.4".
warning "react-scripts > @typescript-eslint/eslint-plugin > ***@***.***"
has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >=
3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta
|| >= 3.7.0-dev || >= 3.7.0-beta".
warning "recharts > ***@***.***" has incorrect peer
dependency "react@^16.0.0".
warning "recharts > ***@***.***" has incorrect peer
dependency "react-dom@^16.0.0".
warning "recharts > ***@***.***" has incorrect peer dependency
"react@^15.0.0 || ^16.0.0".
warning "recharts > ***@***.***" has incorrect peer dependency
"react-dom@^15.0.0 || ^16.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 8.56s.
(venv) ***@***.***:~/srik/ws/websocket-example/frontend$ ls
node_modules  package.json  public  src  yarn.lock
(venv) ***@***.***:~/srik/ws/websocket-example/frontend$
yarn start
yarn run v1.22.10
$ react-scripts start
/home/iibadmin/srik/ws/websocket-example/frontend/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:29
} catch {}
       ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>
(/home/iibadmin/srik/ws/websocket-example/frontend/node_modules/terser-webpack-plugin/dist/index.js:24:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this
command.
(venv) ***@***.***:~/srik/ws/websocket-example/frontend$

**Comment by ustropo** [comment]
Upgrade your `nodejs` version. I used `12.16.2`, but anything above should do it.

You can use `nvm` to install more than one node version in your machine.

**Comment by pvssrikanth** [comment]
Respected Sir,

Thanks a lot finally able to successfully run frontend. Looks like very
exiting although donnot know how to test this websocket

[image: image.png]

**Comment by pvssrikanth** [comment]
Dear Sir,

I am getting following error

[image: image.png]

**Comment by pvssrikanth** [comment]
Dear Sir,

On console

[image: image.png]

**Comment by pvssrikanth** [comment]
Sir,
Sorry for so many emails, After running on localhost its working fine

[image: image.png]

I have one basic question sir, Actually i liked your project very much have
few basic questions.

Separation of Backend and Frontend looks so good

Actually we have a  requirement to create a Interactively Web Applilcation
where all stakeholders who login should get immediate change notifications
on insurance.

Indian Insurance Companies around 50 in number will login to Websocket
application like you developed and raise registration, enrollment , claims
etc.

so will this be a good example to create real time web application like you
developed . so that any entity who raises claims will be seen immediately
real time by other entity who has logged into the application.

Please advise.

Regards,

**Comment by pvssrikanth** [comment]
Dear Sir,
I need your guidance on one question.

We are buidling to develop webapplication and webservice using WebSocket +
fastapi

the webappliation and restful clients submit data for registration form and
that data should be stored in rabbitmq and the consumers who subscribe to
this message will get automatic events of the changes using websocket.

Do you have any reference project like this if not.

How much time and amount you will take to develop this project

Please help us.

Thanks & Regards
srikanth

**Comment by pvssrikanth** [comment]
Dear Sir,
While running your project example  only on the virtual machine where
ubuntu installed the websockerts frontend working on loopback 127.0.0.1 HOW
TO RUN THIS ON ALL IP 0.0.0.0

1daf3fa8da3b
(env) ***@***.***:~/srik/ws/websocket-example/backend$
uvicorn run:app --host=0.0.0.0
INFO:     Started server process [13072]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     192.168.211.12:49299 - "GET /docs HTTP/1.1" 200 OK
INFO:     192.168.211.12:49299 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     192.168.211.12:49298 - "GET / HTTP/1.1" 404 Not Found
INFO:     192.168.211.12:49298 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     192.168.211.12:49298 - "GET /docs HTTP/1.1" 200 OK
INFO:     192.168.211.12:49298 - "GET /dock HTTP/1.1" 404 Not Found
INFO:     192.168.211.12:49315 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     192.168.211.12:49316 - "GET /redocs HTTP/1.1" 404 Not Found
INFO:     192.168.211.12:49317 - "GET /redocs HTTP/1.1" 404 Not Found
INFO:     192.168.211.12:49317 - "GET / HTTP/1.1" 404 Not Found
INFO:     192.168.211.12:49318 - "GET /docs HTTP/1.1" 200 OK
INFO:     192.168.211.12:49318 - "GET /openapi.json HTTP/1.1" 200 OK



a new websocket to create.
INFO:     ('127.0.0.1', 50600) - "WebSocket /ws" [accepted]
a new websocket to create.
INFO:     ('127.0.0.1', 50694) - "WebSocket /ws" [accepted]
a new websocket to create.
INFO:     ('127.0.0.1', 50838) - "WebSocket /ws" [accepted]
error: 1001
Bye..

Please help how to make changes to run this on all ports 0.0.0.0 so that we
can  test it from LAN.

Thanks

**Comment by pvssrikanth** [comment]
Dear Sir,
Finally with a change from loopback to  system ip and built yarn build and
yarn start

i was able to view on LAN

[image: image.png]

It looks very exiting example , If i can customize this projecdt to receive
data for different soures it will be excellent

Thanks
